### ISSUE TITLE
Add support for uni v3 quotes 

### ISSUE THREAD

**Issue by storming0x** [yearn/yearn-lens#13]
https://github.com/yearn/yearn-lens/blob/master/contracts/Oracle/Calculations/Sushiswap.sol#L6

In this part the contract supports only uni v2 router quotes but in newer chains like arbitrum and optimism we only have sushi and uni v3 to work with.

Also may be good to update to use v3 as a source of pricing to this.

**Comment by ControlCplusControlV** [comment]
Can I take this issue?

**Comment by 0xkofee** [comment]
Gonna take a stab at this. seems like one just needs to make a new Calculations file for uni v3 which will eventually get called and succeed when all the other Calculations files revert.

**Comment by 0xkofee** [comment]
Some note taking on my side. may edit later as well...

## Uniswap v3 Pools

A pool is a tuple with two tokens and a fee

- https://docs.uniswap.org/protocol/reference/core/UniswapV3Factory#createpool
- https://github.com/Uniswap/v3-core/blob/v1.0.0/contracts/UniswapV3Factory.sol#L45

### Problem

When `getPriceUsdc` is called, there is no way to know which fee tier to use in order to identify the pool. It's possible for a token pair to utilize all fee schedules therefore multiple pools would exist per pair (one for each fee).

According to the whitepaper, fee tiers can be expanded past the initial three. A solution should exist to handle this scenario. See page 3 in https://uniswap.org/whitepaper-v3.pdf

All three fee tiers are used for the eth-usdc pair for example:

- https://etherscan.io/address/0x1f98431c8ad98523631ae4a59f267346ea31f984#readContract
  - 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
  - 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
  - [500, 3000, 10000...?]

The solutions are:

- Loop through all known fee values (with known fee values updatable somehow) and average out the price from all pools. The problem with this solution is that if one pool is drained then the average will be affected. Another problem is that if a pool returns 0 (because a pool doesn't exist for that fee), then you would need to add in logic to exclude that calc.
- Return the first pool that has data. This should roughly match the other pools. Has the same problem as solution number one but also has another problem on the dependencies on arbitrageurs to keep all the pools in line.
- Have an oracle that stores the "best" reference fee for the given pair. We can then always assume that the fee provided will provide the pool with the best price. The con of this solution is that this list of fees would need to be updated constantly as new pools emerge

**Comment by 0xkofee** [comment]
the pr was merged https://github.com/yearn/yearn-lens/pull/43/files

**Comment by 0xkofee** [comment]
@storming0x can we close? thx

**Comment by jstashh** [comment]
thanks @0xkofee!
